### PR TITLE
Add csv files so we can view the lists on GitHub

### PR DESCRIPTION
**Pull request by harupy**

### CODE REVIEW

**Comment by harupy** [comment]
https://github.com/harupy/engineer-vocabulary-list/blob/add-markdown/Engineer%20Vocabulary%20List.md

**Comment by harupy** [comment]
I wrote a simple python script to convert the excel file to markdown. I'd be happy to commit the script if necessary.

**Comment by davidstosik** [comment]
I think this is a fantastic idea. 👏 
Open, plain text files make this repository a lot more useful than an XLSX file. 👍
(I'd even go as far as to say Google Sheets would have been a better medium than GitHub to share a spreadsheet. 😉)

I don't know whether this PR includes all terms from the XSLX, and maybe the format could be refined (one file per list? table needs more room for optimal readability? etc), but this looks good already.

It looks like GitHub is [able to render CSV files](https://docs.github.com/en/free-pro-team@latest/github/managing-files-in-a-repository/rendering-csv-and-tsv-data). Maybe that would be an even more useful format to publish? (Can be more directly used by scripts that want the data, and can still look good/OK in a browser.)

**Comment by harupy** [comment]
@davidstosik Thanks for the comment! I have created a csv file which looks much better than a markdown table:
https://github.com/mercari/engineer-vocabulary-list/blob/d1852481ad4ce97aeb2c9893ebb17adcf685655d/Engineer%20Vocabulary%20List.csv

**Comment by davidstosik** [comment]
Looks great! 👏 

Nitpick: what do you think of:
- splitting the file in `list_1.csv`, `list_2.csv`, `list_3.csv`, etc., according to the original grouping?
- removing the `#` column (which has become nothing more but the index of the line the item is at)?

**Comment by harupy** [comment]
@davidstosik Agree with both points!

**Comment by harupy** [comment]
@jollyjoester It's ready for review :)

**Comment by jollyjoester** [comment]
@harupy @davidstosik LGTM👍

Thank you for your contribution. It's brilliant work! 
We are very happy that you made the lists better😊

**Pull request merged**
